Repository JNU-econovation/econo-recruit-fe, pull requests merged in 2024-08, with the labels that each got.

#157 feat: current generation 업데이트
  frontend/app/(WithNavbar)/layout.tsx
  frontend/app/kanban/[generation]/detail/page.tsx
  frontend/components/common/navbar/Navbar.tsx
  frontend/components/common/navbar/NavbarCell.tsx
  frontend/components/common/navbar/NavbarGenerationToggle.tsx
  frontend/components/common/navbar/NavbarOperation.tsx
  frontend/components/kanban/column/ColumnWithBackButton.component.tsx
  frontend/public/icons/lt.icon.white.svg
  frontend/src/constants/applicant/28.ts
  frontend/src/constants/applicant/28/designer.ts
  frontend/src/constants/applicant/28/developer.ts
  frontend/src/constants/applicant/28/manager.ts
  frontend/src/constants/application/28.ts
  frontend/src/constants/application/28/designer.ts
  frontend/src/constants/application/28/developer.ts
  frontend/src/constants/application/28/manager.ts
  frontend/src/constants/index.ts
  frontend/src/hooks/useCreateQueryString.tsx
Labels: feature

#164 test: 두번째 기본 인적 사항 테스트 코드 작성
  frontend/cypress/e2e/application.second-personal-information.cy.ts
  frontend/cypress/support/commands.ts
Labels: test ✅

#166 test: 신청폼 희망분야 페이지 e2e 테스트 작성
  frontend/cypress/e2e/application.chapter.cy.ts
  frontend/cypress/support/commands.ts
Labels: test ✅

#167 test: 첫번째 인적사항 페이지 테스트 코드
  frontend/cypress/e2e/application.personal_info.cy.ts
Labels: test ✅

#172 test: 기타 질문 사항 e2e 테스트
  frontend/cypress/e2e/application.other-questions.cy.ts
  frontend/cypress/support/commands.ts
Labels: test ✅

#171 test: 지원 동기 페이지 e2e 테스트 작성
  frontend/cypress.config.ts
  frontend/cypress/e2e/application.chapter.cy.ts
  frontend/cypress/e2e/application.motivation.cy.ts
  frontend/cypress/support/commands.ts
Labels: test ✅

#174 refactor: 신입 모집 마감 날짜 수정
  frontend/src/constants/application/28.ts
  frontend/src/hooks/useApplication.tsx
Labels: invalid
