Repository JNU-econovation/econo-recruit-fe, pull requests merged in 2024-09, with the labels that each got.

#178 refactor: 지원서 제출 시 문자 내용 수정, 지원서 제출 시 보여지는 화면 글 수정
  frontend/app/application/backup/route.ts
  frontend/app/application/done/page.tsx
  frontend/src/constants/application/28.ts
Labels: refactor

#182 bug: 이메일 보내는 요청 주석 처리
  frontend/app/application/backup/route.ts
Labels: bug

#192 feat: 칸반보드 조회 API 수정
  frontend/components/kanban/DragDrop.component.tsx
  frontend/components/kanban/column/ColumnWithBackButton.component.tsx
  frontend/src/apis/kanban/index.ts
Labels: feature

#197 feat: 칸반 보드 페이지에서 지원자의 지원 상태를 카드에 보여준다.
  frontend/components/kanban/card/Card.component.tsx
  frontend/components/kanban/card/CardApplicantStatusLabel.tsx
  frontend/src/apis/kanban/index.ts
  frontend/src/stores/kanban/Kanban.atoms.ts
Labels: feature

#201 hotfix: 빌드 시 발생하는 오류 제거
  frontend/src/stores/kanban/Kanban.atoms.ts
Labels: bug

#207 fix: 기획자 포트폴리오가 보이지 않는 문제 해결
  frontend/components/applicant/applicantNode/Portfolio.tsx
Labels: bug

#213 feat: 지원현황/면접기록 목록페이지에서 합불상태를 조회할 수 있다.
  frontend/components/applicant/Board.tsx
  frontend/components/common/board/Board.tsx
  frontend/components/common/board/BoardCell.component.tsx
  frontend/components/common/board/BoardModal.tsx
  frontend/components/common/board/BoardTable.tsx
  frontend/components/interview/Board.tsx
  frontend/components/passState/PassStateLabel.tsx
  frontend/src/apis/interview/index.ts
  frontend/src/constants/index.ts
  frontend/src/functions/replacer.ts
  frontend/src/hooks/useModalState.ts
  frontend/src/hooks/useSearchQuery.tsx
Labels: enhancement, feature

#211 fix: 관리자가 아닌 사용자에게 navbar에 불필요한 문자가 보이는 버그 수정
  frontend/components/common/navbar/NavbarManagePassState.tsx
Labels: bug

#208 feat: 칸반보드 상세 페이지에서 지원 상태 확인 및 지원 상태 변경 가능하게 구현
  frontend/components/applicant/DetailLeft.component.tsx
  frontend/components/applicant/applicantNode/CustomResource.component.tsx
  frontend/components/kanban/column/ColumnWithBackButton.component.tsx
  frontend/src/apis/applicant/index.ts
  frontend/src/utils/applicant/index.ts
Labels: feature

#216 [FE] fix: 칸반보드의 라벨이 계속 늘어나는 문제 해결
  frontend/components/applicant/applicantNode/Label.component.tsx
  frontend/components/kanban/content/work/Label.component.tsx
  frontend/src/apis/applicant/index.ts
  frontend/src/apis/work/index.ts
Labels: bug

#224 bug: 지원자의 프로토콜이 붙지 않은 포트폴리오 링크에 대한 버그 수정
  frontend/components/applicant/applicantNode/Portfolio.tsx
  frontend/src/utils/applicant/index.ts
Labels: bug

#225 docs: 문서 기여 가이드 및 템플릿 최신화
  .github/ISSUE_TEMPLATE/기능구현.md
  .github/ISSUE_TEMPLATE/리팩터링.md
  .github/ISSUE_TEMPLATE/버그리포트.md
  .github/ISSUE_TEMPLATE/버그리포트.yml
  .github/ISSUE_TEMPLATE/버그수정.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#227 bug: 잘못된 api 파라미터 수정
  frontend/components/interview/Board.tsx
  frontend/components/interview/PageNavbar.tsx
  frontend/src/apis/interview/index.ts
Labels: bug

#229 refactor: 프로토콜이 붙지 않은 url에 대해서 프로토콜을 붙여주는 로직 삭제
  frontend/components/applicant/applicantNode/Portfolio.tsx
  frontend/src/utils/applicant/index.ts
Labels: refactor
