Repository JNU-econovation/econo-recruit-fe, pull requests merged in 2025-03, with the labels that each got.

#240 feat: 면접기록/지원현황 페이지 검색 기능
  frontend/app/(WithNavbar)/applicant/[generation]/page.tsx
  frontend/app/(WithNavbar)/interview/[generation]/page.tsx
  frontend/components/applicant/ApplicantList.tsx
  frontend/components/applicant/Board.tsx
  frontend/components/applicant/PageNavbar.tsx
  frontend/components/common/LoadingSpinner.tsx
  frontend/components/common/Search.tsx
  frontend/components/common/board/Board.tsx
  frontend/components/common/board/BoardTable.tsx
  frontend/components/common/board/types.ts
  frontend/components/interview/Board.tsx
  frontend/components/interview/InterviewerList.tsx
  frontend/components/interview/PageNavbar.tsx
  frontend/components/interview/modal/score/AvgScore.tsx
  frontend/components/interview/modal/score/MyScoreForm.tsx
  frontend/src/apis/applicant/index.ts
  frontend/src/apis/interview/index.ts
  frontend/src/apis/search/index.ts
  frontend/src/hooks/applicant/useApplicantPaginationParams.ts
  frontend/src/hooks/interview/useInterviewerPaginationParams.ts
  frontend/src/hooks/useSearchQuery.tsx
Labels: enhancement, feature

#249 feat: 29기 지원서 질문 데이터 추가
  frontend/app/application/page.tsx
  frontend/components/applicant/DetailRight.component.tsx
  frontend/components/applicant/applicantNode/CustomHuman.component.tsx
  frontend/components/application/Navbar.tsx
  frontend/components/application/applicationLayout/BooleanTextarea.component.tsx
  frontend/components/application/applicationLayout/Horizontal.componet.tsx
  frontend/components/application/applicationLayout/RadioForCheck.component.tsx
  frontend/components/application/applicationLayout/Vertical.component.tsx
  frontend/components/application/applicationLayout/timeline/Timeline.component.tsx
  frontend/components/application/applicationNode/Radio.tsx
  frontend/src/constants/applicant/25.ts
  frontend/src/constants/applicant/26.ts
  frontend/src/constants/applicant/27.ts
  frontend/src/constants/applicant/28.ts
  frontend/src/constants/applicant/29.ts
  frontend/src/constants/applicant/29/designer.ts
  frontend/src/constants/applicant/29/developer.ts
  frontend/src/constants/applicant/29/manager.ts
  frontend/src/constants/applicant/type.d.ts
  frontend/src/constants/application/29.ts
  frontend/src/constants/application/29/designer.ts
  frontend/src/constants/application/29/developer.ts
  frontend/src/constants/application/29/manager.ts
  frontend/src/hooks/useApplication.tsx
Labels: feature

#253 feat: 지원 페이지에서 사용자가 입력한 질문만 색이 진해지도록 네비게이션바 수정
  frontend/app/application/page.tsx
  frontend/components/application/Layout.component.tsx
  frontend/components/application/Navbar.tsx
  frontend/components/application/Question.component.tsx
  frontend/components/application/Question.tsx
  frontend/components/application/applicationLayout/BooleanTextarea.tsx
  frontend/components/application/applicationNode/NextButton.tsx
  frontend/components/application/loader/Navbar.skeleton.tsx
  frontend/components/application/loader/Question.skeleton.tsx
  frontend/src/functions/application.ts
  frontend/src/hooks/useApplication.tsx
  frontend/src/hooks/useApplicationIndexControl.hook.tsx
  frontend/src/hooks/useFlushInterval.tsx
  frontend/src/stores/application/index.ts
Labels: feature

#262 fix: 개발자 질문의 5번과 7번이 동일하게 입력되는 버그 수정
  frontend/src/constants/application/29/developer.ts
Labels: bug

#266 fix: canApplicationNext 에서 오류 메세지가 없을 때 true 리턴하도록 수정
  frontend/src/hooks/useApplication.tsx
Labels: bug

#267 refactor: 29기 지원서 요구사항 반영
  frontend/components/application/applicationNode/RadioByTwoRank.component.tsx
  frontend/src/constants/application/29/manager.ts
Labels: refactor

#271 bug: 기본 인적 사항의 학년과 학기가 undefined로 표시되는 문제 해결
  frontend/src/constants/application/29.ts
Labels: bug

#270 fix: 필수 확인 사항 질문의 input 의 validate가 '확인했습니다.'가 포함되어있는지를 확인하도록 수정
  frontend/src/functions/validator.ts
Labels: bug

#275 fix: 개발자의 7번 질문의 답변이 보이지 않던 버그 수정
  frontend/src/constants/applicant/29/developer.ts
Labels: bug

#278 fix: 칸반보드 상세 페이지에서 구체적인 분야 불러오기
  frontend/src/constants/index.ts
Labels: bug

#276 refactor: 합/불 라벨링 사용자 피드백 추가 & 공통 로직 설정
  frontend/components/applicant/_applicant/ApplicantDetailLeft.tsx
  frontend/components/applicant/_applicant/_applicantNode/CustomResource.tsx
  frontend/components/applicant/applicantNode/CustomResource.component.tsx
  frontend/components/common/CardApplicantStatusLabel.tsx
  frontend/components/kanban/card/Card.component.tsx
  frontend/components/passState/ApplicantsList.tsx
  frontend/src/functions/passState.ts
  frontend/src/hooks/applicant/useApplicantById.tsx
  frontend/src/hooks/applicant/useOptimisticApplicantPassUpdate.tsx
  frontend/src/hooks/useModalState.ts
Labels: enhancement, refactor

#280 feat: 면접관 리스트 조회 API의 스팩 변경 및 면접관 리스트 조회 시 "현재 기수 면접관"만 조회하도록 수정
  frontend/app/(WithNavbar)/admin/[generation]/page.tsx
  frontend/components/admin/Board.component.tsx
  frontend/package.json
  frontend/src/apis/applicant/index.ts
  frontend/src/apis/interview/index.ts
  frontend/src/apis/work/index.ts
Labels: feature

#282 refactor: 인재상 변경에 따른 record 점수 필드 변경
  frontend/components/interview/modal/score/AvgScore.tsx
  frontend/components/interview/modal/score/InterviewScore.tsx
  frontend/components/interview/modal/score/InterviewerScore.tsx
  frontend/components/interview/modal/score/MyScore.tsx
  frontend/components/interview/modal/score/MyScoreForm.tsx
  frontend/components/interview/modal/score/ScoreCell.tsx
  frontend/components/interview/modal/score/ScoreInput.tsx
  frontend/src/constants/applicant/29.ts
  frontend/src/functions/formatter.ts
Labels: refactor

#284 feat: pagination page의 prefetch 로직
  frontend/app/(WithNavbar)/interview/[generation]/page.tsx
  frontend/components/applicant/ApplicantList.tsx
  frontend/components/applicant/PageNavbar.tsx
  frontend/components/common/PageNavbar.component.tsx
  frontend/components/interview/IntervieweeList.tsx
  frontend/components/interview/InterviewerList.tsx
  frontend/components/interview/PageNavbar.tsx
  frontend/src/hooks/applicant/index.ts
  frontend/src/hooks/applicant/useApplicantPaginationParams.ts
  frontend/src/hooks/applicant/useApplicantsQuery.ts
  frontend/src/hooks/interview/index.ts
  frontend/src/hooks/interview/useAllInterviewRecordQuery.ts
  frontend/src/hooks/interview/useIntervieweePaginationParams.ts
  frontend/src/hooks/interview/useInterviewerPaginationParams.ts
Labels: enhancement, convention
